---
- hosts: all
  gather_facts: false
  become: yes
  tasks:
  - name: file creation
    file:
       path: /home/ubuntu/tst.txt
       state: touch
       owner: vin1
       group: sudo
       mode: 0644
